services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"   # access at http://localhost:5678
    environment:
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - TZ=Asia/Ho_Chi_Minh
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files   # nếu muốn mount thêm thư mục local vào container
    
  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333 # REST API
      - 6334:6334 # GRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    # environment:
      # - QDRANT_API_KEY=your_secure_api_key # Optional: for API key authentication

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"   # API endpoint
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  n8n_data:
  qdrant_storage:
  ollama_data: